name: Deploy Docker image to Dockerhub

on:
  push:
    branches: ['*']

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  validate:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: true

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check if deploy branch
      id: is_deploy_branch
      run: |
        branch_name=$(git branch --show-current)
        echo "Branch name: $branch_name"
        export is_deploy_branch=true
        if [[ "$branch_name" =~ ^v[0-9]+\.[0-9]+$ ]]; then
          echo "Branch name matches with version release."
          export version_number=${branch_name#v} # remove the "v" prefix
          echo "VERSION_NUMBER=$version_number" >> $GITHUB_ENV
        elif [[ "$branch_name" == "master" ]]; then
          echo "Branch name is 'master'. Setting VERSION_NUMBER as 'latest'..."
          export VERSION_NUMBER=latest
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV
        else
          echo "Branch name does not match pattern. Stopping the workflow..."
          export is_deploy_branch=false
        fi
        echo "is_deploy_branch=$is_deploy_branch" >> $GITHUB_OUTPUT

    - name: Checkout repository
      if: steps.is_deploy_branch.outputs.is_deploy_branch == 'true'
      uses: actions/checkout@v3

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t aws-eks-helm-deploy:${{ env.VERSION_NUMBER }} .

    - name: Tag Docker image
      run: docker tag aws-eks-helm-deploy:${{ env.VERSION_NUMBER }} qitpy/aws-eks-helm-deploy:${{ env.VERSION_NUMBER }}

    - name: Push Docker image
      run: docker push qitpy/aws-eks-helm-deploy:${{ env.VERSION_NUMBER }}
