name: Docker Image CI

on:
  push:
    branches: [ "feat/config-deploy-branch" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  display-branch-names:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display branch names
        run: |
          git fetch
          git branch | awk '{print $NF}'
